### ISSUE TITLE
Should it be possible exclude radars?

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#1]
@CeciliaNilsson709 Is there a need to exclude certain radars from the visualization or can we always use all radars from a country?

* If we can always use whole countries, we don't need to provide a list of radars (just a list of countries: simple).
* If we want to exclude radars, we will need to provide a list of all radars for each country (except the ones we don't want) or provide some extra functionality to *exclude* specific countries.

**Comment by peterdesmet** [comment]
A well, it seems we'll have to define a list of radars anyway, as it is a required argument for downloading data. Still, would be good to know. 😄

**Comment by CeciliaNilsson709** [comment]
Ok, and yes we will anyway need to be able to exclude radars site by site, as some issues only affect individual stations.

**Comment by peterdesmet** [comment]
Can now be done in the settings file.
