### ISSUE TITLE
How to handle NA values in aggregation

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#10]
I made a first pass at aggregating data. Here's the data for the radar `seang`, aggregated **by hour** (so generally four 15-minute h5 files bundled up) and in **3 height bands** (200 <= x < 1000, 1000 <= x < 2000, 2000 <= x < 3000):

![aggregation](https://cloud.githubusercontent.com/assets/600993/26143908/30724684-3ae7-11e7-9a0c-0707efe4a6f7.png)

For now, I just took the **mean** `u`, `v` and `dens`, but that will result in a lot of `NA` values, as even one `NA` value across the heights or times would result in a `NA` average. Maybe that's OK or maybe some `NA` should be coerced to 0 before aggregation?

## How have we done this before?

For reference, this is the [SQL aggregation we did for the flow viz](https://github.com/enram/case-study/tree/master/data/bird-migration-altitude-profiles#procedure-for-aggregating-the-data), which consists of 2 parts:

### Conditions

> Only consider speed if the radial velocity standard deviation is above or equal to 2 (to make sure we are only considering birds) and the bird density is above or equal to 1 birds/km3 (for more precise bird speed).

The >=2 for radial velocity deviation is already done in the h5 files, but not the >=1 birds/km3. Is it necessary we do this?? I'd prefer to avoid this. See also #8

### Aggregation

> For u speed/v speed:
> * Average the speeds, if at least one of the altitudes within the altitude band has a speed which met the conditions.
> * Set the speed to 0 if none of the altitudes within the altitude band has a speed which met the conditions, but there were originally speeds detected.
> * Keep null if no speeds were detected.

From the SQL, I think that is incorrect, it should be:

> For u speed/v speed:
> * If speeds were detected for **all** altitudes and across the whole time interval and **all** of those met the conditions, then average those speeds.
> * If speeds were detected for **all** altitudes and across the whole time interval, but **not all** of those met the conditions, then the average speed is set to 0
> * If any of the speeds for all altitudes and across the whole time interval was `null`, then the average speed is `null`

That gives a lot of importance to `NA` values too. We didn't really see an affect, because speeds were detected for most altitudes, but I'll look for an example to verify.

In any case, is there something we should do to avoid a single `NA` value resulting in an `NA` average?

**Comment by hvangasteren** [comment]
It's important that altitude bins agree to the conditions mentioned above (radial velocity and density). Only then they relate to bird speeds and/or densities. The value of '>1' for density is to get rid of small errors which hardly effect density, but **DO** for speed. So I prefer to include that one. Furthermore, I guess the aggregation was done well, and skip null values in the calculations. They may not relate int NA values!

**Comment by peterdesmet** [comment]
@hvangasteren OK, so if bird density < 1, I'll set the speeds to NA? The radial velocity processing is already done.

> Furthermore, I guess the aggregation was done well, and skip null values in the calculations. They may not relate into NA values!

We didn't have null values in the case study data, so the issue did not come up. Here we do. So the question is: how do I deal with that?

1. Don't deal with it: even one NA value should result in an average of NA?
2. Skip NA values: even one not-NA value should result in an not-NA average?
3. Other?

**Comment by hvangasteren** [comment]
> OK, so if bird density < 1, I'll set the speeds to NA? 

This is correct and I would choose option two. If there is some data, you should get some result.

**Comment by peterdesmet** [comment]
@hvangasteren OK, will add that bird density < 1 => NA condition. I also like the second option (some data => some result). So, the whole process in pseudocode will be:

```
CONDITIONS
if radial velocity < 2 => speed is NA (already done in h5 files)
if bird density < 1 => speed is NA
else leave speed as it is

AGGREGATION
if all speeds within the bin/interval are NA => average speed is NA
if even one speed within the bin/interval is not NA => average speed is not NA
```

That means we're not setting speeds to 0 (like we did for the case study), but I'm not sure how we can fit it in here, with the first CONDITION already applied.

**Comment by jshamoun** [comment]
When there is missing data it should be NA. I agree with the last thread that if there there is a speed within bin/interval it should be used.

I think we do want speed = 0 when there is no migration. At least when there is no migration within an aggregate being visualized. To be sure though, I would need some examples to see the consequences of different treatments. At least this was important for the flow visualization because it influences interpolation in space and time. If I am not mistaken, speed = 0 when migration = 0. No migration = no speed, no data = NA. Yet, if you calculate an average speed, 0 will have a huge impact and does not make biological sense during migration. This feels like deja vu. I know we have had this discussion before.

**Comment by peterdesmet** [comment]
We have had this discussion before, but the data (case study) was quite different from what we have now: no NA values vs lots of NA values (=> lots of which are probably set to NA because radial velocity condition was not met).

I'll try to make an example.

**Comment by adokter** [comment]
Hi, these are the conventions in ODIM and bioRad:

* `NA` in bioRad maps to `nodata` in the ODIM convention: value to denote areas void of data (never radiated)
* `NaN` maps to `undetect` in the ODIM convention: denote areas below the measurement detection threshold (radiated but nothing detected). The value is also used when there are too few datapoints to calculate a quantity.
* 0 Maps to 0 in the ODIM convention: denote areas where the quantity has a measured value of zero (radiated and value zero detected or inferred).

**Comment by peterdesmet** [comment]
@adokter should look for it more carefully, but thus far I have not encountered 0 speeds in the sample data. Not sure about `NaN` vs `NA`: does it make a difference for the aggregation we're discussing here?

**Comment by peterdesmet** [comment]
Here's a simple example: let's say I'm aggregating on 30 minutes (combining 20:00 and 20:15) and 3 height intervals (200-400-600, 800-1000-1200, 1400-1600-1800). That will result in 3 groups for the data below (separated by a red line):

![bins_1](https://cloud.githubusercontent.com/assets/600993/26163725/c41acba2-3b2a-11e7-88fa-a6f4f3c3b94c.png)

_Note: the blue box indicates a u and v speed which would be set to `NA` based on the bird density < 1, were it not that those speeds were already `NA` in the h5 data._

The result of the aggregation is:

<img width="1074" alt="bins_2" src="https://cloud.githubusercontent.com/assets/600993/26163731/c732c542-3b2a-11e7-898c-9e8c5c7146a5.png">

Were we would take the approach of using the averages that ignore na values (e.g. `u_avg_no_na`).

@adokter @jshamoun @hvangasteren does that seem ok?

**Comment by hvangasteren** [comment]
@peterdesmet values which don't agree with the conditions should actualy by set to `NaN,` according to ODIM rules from @adokter. The result will be the same. 
One other question I have @adokter is why there are so many `NA` values in the above example. At higher altitudes you would expect zero migration, but not `nodata`

**Comment by CeciliaNilsson709** [comment]
@hvangasteren thats actually an issue with this partricular radar, all data is beeing cut at 1 km. So it will probably not make it in to the final data set (and a good exempel of why we need to exclude some sites).

**Comment by peterdesmet** [comment]
@CeciliaNilsson709 aha, looks like I should not have picked the alphabetically first radar. 😄 @hvangasteren for e.g. `searl` I do get `NaN` values, but as you say, they will be treated just like the `NA` values.

**Comment by adokter** [comment]
@peterdesmet in response to https://github.com/enram/timamp-etl/issues/10#issuecomment-302138533, yes I would average with `xxx_avg_no_na`. But it is important to preserve the difference between `NA` and `NaN`, it simply isn't the same and important to distinguish between altitude layers without data because the layer wasn't radiated, versus the case when there was nothing detected.

Non-radiated layers can occur when
* a radar is on a mountain, and doesn't cover the lower altitudes
* when a radar has only low elevation scans, so the higher altitudes are never radiated

**Comment by adokter** [comment]
so i would suggest that `avg_no_na` gives the averaged values of the subset of numeric values if they are present. But when it acts on a list of only `NA` values it should give `NA` and when it acts on a list of only `NaN` values it gives `NaN`, and when it acts on a set containing both `NaN` and `NA` it gives `NaN`

**Comment by peterdesmet** [comment]
Ok, https://github.com/enram/timamp-etl/issues/10#issuecomment-302226525 makes sense and I could export the data to CSV like that. But for the visualization it won't make any difference. Will those CSV be used for anything else?

**Comment by peterdesmet** [comment]
The difference between NaN and Na is [mentioned in the documentation](https://github.com/enram/vp-processing/blob/master/src/extract_vp.Rmd#export-to-a-csv-file), but handled the same towards the CSV output. Closing this issue.
