### ISSUE TITLE
Which time interval bins do we want?

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#11]
How do we want to aggregate across time? I guess it depends on which aggregation still makes sense to see the details, but also allows to navigate through the whole flyway time series (which is days? weeks?). Does an aggregation on `hour` (as shown below) make sense?

```
floor date_time on hour:
2016-10-03 19:45:00 -> 20161003 1900
2016-10-03 20:00:00 -> 20161003 2000
2016-10-03 20:15:00 -> 20161003 2000
2016-10-03 20:30:00 -> 20161003 2000
2016-10-03 20:45:00 -> 20161003 2000
2016-10-03 21:00:00 -> 20161003 2100

2016-10-03 19:53:00 -> 20161003 1900
2016-10-03 20:08:00 -> 20161003 2000
2016-10-03 20:23:00 -> 20161003 2000
2016-10-03 20:38:00 -> 20161003 2000
2016-10-03 20:53:00 -> 20161003 2000
2016-10-03 21:08:00 -> 20161003 2100
```

**Comment by CeciliaNilsson709** [comment]
We will include data from the 19/9 to the 9/10, so 20 days.  For the analysis I think we will mostly be working with nightly means per station. What do you think, does it make sense to do that for the visualization as well? Or will that be too coarse?

**Comment by peterdesmet** [comment]
Nightly means will probably be a bit too coarse for the visualization, especially the animated flow viz (will look "jumpy"). If we use per hour, we'll get 24 hours * 20 days = 480 steps, which is a bit fewer than what we have for the case study: 24 hours * 3 per hour (20 min) * 7 days = 504 steps. I'll try that and we can adapt to something that works.

**Comment by peterdesmet** [comment]
20 days... if I can count right, that is 19/9 inclusive and 9/10 exclusive, right?

**Comment by plieper** [comment]
It should be 19/9 AND 9/10 inclusive, so 21 days actually.

**Comment by plieper** [comment]
It should be 19/9 AND 9/10 inclusive, so 21 days actually.

**Comment by peterdesmet** [comment]
I only got to make some rough, undocumented code to aggregate, but it [is by the hour](https://github.com/enram/vp-processing/blob/master/src/vp_to_flowviz.Rmd#add-time-bins-per-hour). Closing this issue.
