### ISSUE TITLE
Day-night extraction over multiple days

### ISSUE THREAD

**Issue by CeciliaNilsson709** [enram/timamp-etl#17]
When trying to run multiple days at once, I get the error message:

>   |............................................                     |  68%
> label: extract_get_day_and_night
> 
> Quitting from lines 265-275 (vp-processing.Rmd) 
> Error in mutate_impl(.data, dots) : Not a vector
> Calls: <Anonymous> ... mutate -> mutate_ -> mutate_.tbl_df -> mutate_impl -> .Call
> In addition: Warning messages:
> 1: In (function (...)  : Vertical profiles are not from a single radar
> 2: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
> 

So, probably something going wrong with the "date-of-dusk" when there are multiple dates involved?

**Comment by peterdesmet** [comment]
Yeah, that code wasn't really tested. 😬 Can you mail me a small example dataset that spans multiple days?

**Comment by peterdesmet** [comment]
For reference, this [line was causing the error](https://github.com/enram/vp-processing/commit/930738709be13739700f101cd500bcbc802a763c#diff-55b7b137adbcb466b14c0fdcaf0eac28R109):

    mutate(latitude = settings$radars[[radar_id]]$latitude) %>%

This is my understanding of the bug: for a single date, only one radar_id was referenced. But if there were multiple dates, a vector of (identical) radar ids (e.g. `c("nldbl", "nldbl")` would be referenced from the settings, which would break.

This can be solved by creating a dataframe from the settings, with one row for each radar. We then **join** that info. Haven't completely done that yet (and there's still another bug), but at least I know what is causing it. 😌
