### ISSUE TITLE
Obsolete settings files?

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#26]
These files look obsolete, can they be removed?

1. https://github.com/enram/vp-processing/blob/master/settings/flyway_settings_de.yaml -> looks like it's included in the `flyway_settings.yaml`
2. https://github.com/enram/vp-processing/blob/master/settings/flyway_settings_test.yaml -> test?

**Comment by CeciliaNilsson709** [comment]
Japp, dom behövs inte längre så du kan ta bort dom.

**Comment by peterdesmet** [comment]
🗑👌
