### ISSUE TITLE
update filename attribute

### ISSUE THREAD

**Issue by adokter** [enram/timamp-etl#28]
@peterdesmet  I changed vol2bird such that it now stores input and output filename  also as an attribute in the .h5 files. However, due to limitations of a  Baltrad library used to generate the h5 files, I could only store these  attributes under the /how group, not the /what group.

Since accepting pull request adokter/bioRad#38,  the filename of the polar volume is stored under  attributes$what$vp_filename. For consistency, I would like to change  that to attributes$how$filename_vp. But we would have to coordinate to  change that simultaneously in vp_processing and bioRad.

Let me know when  you can change it, than I immediately update bioRad as well.

**Comment by peterdesmet** [comment]
vp-processing is reading from the /how group since 10 months: https://github.com/enram/vp-processing/commit/884b846f7e804ae6efe125c4244921e98ae9a7b6

I just tested it and it works. I'm closing this issue.
