### ISSUE TITLE
How to access v speed data from a vplist object

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#6]
See https://rawgit.com/enram/timamp-etl/read-data/src/2_vp_to_csv.nb.html at the bottom:

I can access `v` data for a single vp file:

    bioRad::fetch(vp_files[1], quantity = "v")

But if I want to access it for 4 vp files (= vplist object):

    bioRad::fetch(vp_files, quantity = "v")

I get the `dens` values back instead of `v` (which is not even the first attribute), even though according to the bioRad documentation, the `fetch` function should work on 3 class types:

> ### Arguments
> 
> x: a vp,vplist or vpts object
> quantity: a profile quantity, one of "HGHT","u","v","w","ff", "dd","sd_vvp","gap","dbz","eta", "dens","DBZH","n","n_all","n_dbz","n_dbz_all".

What am I doing wrong or is this a bug in bioRad? /cc @plieper @adokter

**Comment by peterdesmet** [comment]
This seems like a bioRad issue. Moving it over there: https://github.com/adokter/bioRad/issues/34

**Comment by adokter** [comment]
Fixed by commit https://github.com/adokter/bioRad/commit/5b44f95bd016ac92f7e82ca90837730e054c4498. Please update to the latest release https://github.com/adokter/bioRad/releases/tag/0.2.4

**Comment by peterdesmet** [comment]
Great!
