### ISSUE TITLE
Is radial_velocity_std already used as a threshold

### ISSUE THREAD

**Issue by peterdesmet** [enram/timamp-etl#8]
The first step in the [SQL aggregation step](https://github.com/enram/timamp/blob/master/v2/preprocess/eu15a/input/template.sql) is to use `radial_velocity_std` and `bird_density`as a threshold:

    CASE
            WHEN radial_velocity_std >= 2 AND bird_density >= 1 THEN u_speed
            ELSE NULL
    END AS conditional_u_speed

That is applied to `v`, `u` and `dens`.

I can't find the `radial_velocity_std` in the h5 data, so can I assume that threshold processing (including `bird_density > 1`) is already applied and I can skip that step in the SQL? The definition for [/how/sd_vvp_thresh](https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification) seems to indicate so.

**Comment by adokter** [comment]
Yes the radial velocity threshold has already been applied. Your additional `bird_density` threshold not however.

Two things to note:
* your `radial_velocity_std` is the same as `sd_vvp` in the hdf5 profile
* the conditions in your `WHEN` statement need not be optimal for all users / radars, that's why in bioRad you can change these post-hoc thresholds if you want

**Comment by peterdesmet** [comment]
Ok, great! I'll add `sd_vvp` to the output data.

Since the whole process is to visualize data and those will be aggregated a lot, I'd rather take the same approach for all data as a first attempt. That means I'll skip the conditional processing in the SQL and take the (radial velocity processed) h5 data at face value.

**Comment by peterdesmet** [comment]
Aha, for the [NL-BE case study data](https://github.com/enram/case-study/tree/master/data/bird-migration-altitude-profiles) there was not a single `NA` value for u, v, or dens, so that didn't affect any of the aggregation. There are plenty of times were the speeds did not meet the radial velocity standard deviation conditions though, which resulted in 0 speeds.

But for the flyway data (which already went through radial velocity standard deviation processing), we *do* have a lot of `NA` values, so we need a best approach on how to average those.
